package com.saikai.ptt.core.protocol

import com.saikai.ptt.core.common.BinaryUuid
import java.util.UUID

/**
 * Identifies one PTT transmission, from VOICE_START to VOICE_END.
 *
 * Generated by the sender when it presses to talk, and carried in every packet
 * of that transmission. It is what lets a receiver drop packets belonging to a
 * session it has already ended: after a force interrupt the displaced sender may
 * still have frames in flight, and without a session id those frames would be
 * indistinguishable from the new speaker's (ADR-003 section 6).
 *
 * A distinct type from [com.saikai.ptt.core.domain.DeviceId] even though both are
 * 16-byte UUIDs on the wire. They sit next to each other in the header, they are
 * both `uuid`, and the compiler is the only thing that will notice if they are
 * swapped.
 *
 * All-zero means "not a session packet".
 */
@JvmInline
value class SessionId private constructor(private val uuid: UUID) {

    /** Canonical text form, for storage and diagnostics. */
    val value: String get() = uuid.toString()

    /** True for the all-zero id, which non-session packets carry. */
    val isZero: Boolean
        get() = uuid.mostSignificantBits == 0L && uuid.leastSignificantBits == 0L

    /** Writes the 16-byte big-endian form into a caller-owned buffer. */
    fun writeTo(target: ByteArray, offset: Int = 0) {
        require(offset >= 0 && offset + BYTES <= target.size) {
            "Need $BYTES bytes at offset $offset in a ${target.size}-byte buffer"
        }
        BinaryUuid.write(uuid, target, offset)
    }

    /** Allocating convenience for tests and cold paths. */
    fun toBytes(): ByteArray = ByteArray(BYTES).also { writeTo(it) }

    override fun toString(): String = value

    companion object {
        /** Length of the binary form, in bytes. */
        const val BYTES: Int = BinaryUuid.BYTES

        /** The all-zero id: carried by every packet that is not part of a session. */
        val ZERO: SessionId = SessionId(UUID(0L, 0L))

        /** A fresh session identity. One per press of the talk button. */
        fun random(): SessionId = SessionId(UUID.randomUUID())

        /** Parses the canonical text form, or returns null. Never throws. */
        fun parse(text: String?): SessionId? {
            if (text.isNullOrBlank()) return null
            val trimmed = text.trim()
            return try {
                val uuid = UUID.fromString(trimmed)
                if (uuid.toString().equals(trimmed, ignoreCase = true)) SessionId(uuid) else null
            } catch (_: IllegalArgumentException) {
                null
            }
        }

        /** Reads the 16-byte big-endian form, or returns null when the range is short. */
        fun fromBytes(source: ByteArray, offset: Int = 0): SessionId? {
            if (offset < 0 || offset + BYTES > source.size) return null
            return SessionId(BinaryUuid.read(source, offset))
        }
    }
}
